/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.app

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main(args: Array<String>?) {
    println(App().greeting)
    ForLoop(10)
}
